# This workflow will do a clean install of node dependencies, build the source
# code across multiple Node.js versions, and lint the project.

name: Build & Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Default version of Node.js for jobs
  node-version: "12"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["12", "14", "16"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      #- run: yarn run test TODO: Readd once we have tests

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn run lint

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - run: |
          git config user.name "O.A.F."
          git config user.email "<>"
      - run: |
          cp -R mafia mafiafiles
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: |
          git fetch --all
          git switch release
          rm -r scripts/
          rm -r data/
          rm -r relay/
          mv KoLmafia/scripts scripts
          mv KoLmafia/relay relay
          mv mafiafiles/ccs ./ccs
          mv mafiafiles/data ./data
          mv mafiafiles/dependencies.txt dependencies.txt
      - run: |
          git add scripts/
          git add ccs/
          git add data/
          git add relay/
          git add dependencies.txt
          {
            git commit -m "Build Mafia files for commit $GITHUB_SHA"
            git push origin release
          } || exit 0
